version: '3.1'
services:
  postgres:
    container_name: postgres_db
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - docker.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      instagram_net:
        ipv4_address: 192.168.0.2

  pgadmin:
    container_name: pgadmin4
    # links:
    #   - postgres:postgres
    image: dpage/pgadmin4
    ports:
      - 8080:80
    env_file:
      - docker.env

    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    networks:
      instagram_net:
        ipv4_address: 192.168.0.3

# volumes:
#   postgres-data:
#     driver: local

networks:
  instagram_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1
